### ISSUE TITLE
Setup test Database connection

### ISSUE THREAD

**Issue by bfosterscripps** [bfosterscripps/codecrusaders#13]
We need to check to see whether we can access data from the MySQL database hosted by Pellissippi - this will require making the connection in php, and creating the mock data in the MySQL database.

**Comment by GhoulishWorker** [comment]
Use Putty to SSH into our server.
 Use the information suppllied in our Slack to SSH in.

Once you're in you'll want to connect to the SQL by typing in the following command: 
mysql --user=DatabaseUsername --password=DatabasePassword DatabaseName

If you do this correctly, then you'll be connected to the database.

You'll then want to create a table by using the following command:

CREATE TABLE MyGuests (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL
);

Of course, you can change the columns you insert.

To execute the command type \g

Then you'll need to insert data into your table, like so:

INSERT INTO MyGuests (firstname, lastname)
VALUES ('John', 'Doe');

If you do this correctly, you'll now have inserted data into your table.
This can be done again to add more data.

To connect your PHP to your mySQL, you'll need to add a .php file to your server.

## An example of a connection is supplied below: 

<?php
$servername = "localhost:3306";
$username = "DatabaseUsername";
$password = "DatabasePassword";
$dbname = "DatabaseName";

$conn = new mysqli($servername, $username, $password,$dbname);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 
$sql = "SELECT \* FROM MyGuests";
$result = mysqli_query($conn, $sql);
if (mysqli_num_rows($result) > 0) {
    $results = 0;
    while($row = mysqli_fetch_assoc($result)) {
        echo($row["firstname"] . " " . $row["lastname"] . " ");
    }
} else {
    echo "0 results";
}
?>

---

If you set this up correctly, then you should have a list of names on webpage now.
