### ISSUE TITLE
Generate Mock School Data

### ISSUE THREAD

**Issue by bfosterscripps** [bfosterscripps/codecrusaders#17]
Make tables in the MySQL database with mock data representing colleges users might want to attend, with corresponding costs for various degrees.

The data should be semi-realistic, e.g. you might want to use University of Tennessee over Hogwarts.

This task is not to hook the database up to services that provide the data - just for you to make manual inserts into your database to give practical test data.

**Comment by ghost** [comment]
SSH into our server using PuTTY. From there you must enter our database. Most of the information on how to do this can be found under closed issue 13.
